arangodb:
  arangopipe_admin_password: arangopipe
  arangopipe_admin_username: arangopipe
  arangopipe_dbname: arangopipe
  host: http://localhost:8529
  port: 8529
  root_user: root
  root_user_password: open sesame
mlgraph:
  graphname: enterprise_ml_graph
